### PR TITLE
Crypto phasestream2

### PR DESCRIPTION
**Pull request by dominik098**

### CODE REVIEW

**Comment by dominik098** [comment]
@asiahello Let me know if you see some improvements or mistakes here, and I merge this PR.

**Comment by asiahello** [comment]
Dominik, look at my solution, it is bruteforceless and takes <1sec due to reduced loops.

**Comment by dominik098** [comment]
> Dominik, look at my solution, it is bruteforceless and takes <1sec due to reduced loops.

I definietly better solution. You can replace mine.

**Comment by dominik098** [comment]
Or maybe we can leave both, but I don't know if it is a good idea.

**Comment by asiahello** [comment]
I would recommend to replace your solution, because both approaches are only a little bit different,

**Pull request merged**
